name: Docker
on:
  push:
    branches:
      - "main"

jobs:
  build-backend:
    name: "Build (Backend)"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          file: backend/Dockerfile
          tags: |
            ghcr.io/csesoc/cselectives-backend:${{ github.sha }}
            ghcr.io/csesoc/cselectives-backend:latest
          labels: ${{ steps.meta.outputs.labels }}
