name: Docker
on:
  push:
    branches:
      - "develop"

jobs:
  build-backend:
    name: "Build (Backend)"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: backend
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          file: backend/Dockerfile
          tags: |
            ghcr.io/csesoc/cselectives-backend:${{ github.sha }}
            ghcr.io/csesoc/cselectives-backend:latest
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy (CD)
    runs-on: ubuntu-latest
    needs: [build-backend]
    concurrency: staging
    environment:
      name: staging
      url: https://cselectives.staging.csesoc.unsw.edu.au
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: csesoc/deployment
          token: ${{ secrets.GH_TOKEN }}
      - name: Install yq - portable yaml processor
        uses: mikefarah/yq@v4.25.1
      - name: Update deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "CSESoc CD"
          git config user.email "technical@csesoc.org.au"
          git checkout -b update/cselectives/${{ github.sha }}
          yq -i '.items[0].spec.template.spec.containers[0].image = "ghcr.io/csesoc/cselectives-backend:${{ github.sha }}"' apps/projects/cselectives/staging/deploy-backend.yml
          git add . 
          git commit -m "feat(cselectives): update image" 
          git push -u origin update/cselectives/${{ github.sha }}
          gh pr create --title "feat(cselectives): update image" --body "Updates the image for the cselectives deployment to commit csesoc/cselectives-v2@${{ github.sha }}." > URL
          gh pr merge $(cat URL) --squash -d
